-- MySQL Script generated by MySQL Workbench
-- Mon Apr 22 22:28:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema red_social
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `red_social` ;

-- -----------------------------------------------------
-- Schema red_social
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `red_social` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `red_social` ;

-- -----------------------------------------------------
-- Table `red_social`.`credencial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `red_social`.`credencial` ;

CREATE TABLE IF NOT EXISTS `red_social`.`credencial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo_electronico_UNIQUE` (`correo_electronico` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `red_social`.`perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `red_social`.`perfil` ;

CREATE TABLE IF NOT EXISTS `red_social`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `credencial_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `genero` VARCHAR(1) NOT NULL,
  `situacion_sentimental` VARCHAR(45) NULL,
  `lugar_residencia` VARCHAR(45) NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `foto_perfil` VARCHAR(255) NOT NULL,
  `foto_portada` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perfil_cuenta1_idx` (`credencial_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_cuenta1`
    FOREIGN KEY (`credencial_id`)
    REFERENCES `red_social`.`credencial` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `red_social`.`amigos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `red_social`.`amigos` ;

CREATE TABLE IF NOT EXISTS `red_social`.`amigos` (
  `perfil_id` INT NOT NULL,
  `perfil_amigo_id` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`perfil_id`, `perfil_amigo_id`),
  INDEX `fk_perfil_has_perfil_perfil2_idx` (`perfil_amigo_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_has_perfil_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `red_social`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_perfil_has_perfil_perfil2`
    FOREIGN KEY (`perfil_amigo_id`)
    REFERENCES `red_social`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `red_social`.`publicacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `red_social`.`publicacion` ;

CREATE TABLE IF NOT EXISTS `red_social`.`publicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `perfil_id` INT NOT NULL,
  `foto` VARCHAR(255) NULL,
  `cant_likes` INT NOT NULL DEFAULT 0,
  `cant_comentarios` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_publicacion_perfil1_idx` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_publicacion_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `red_social`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `red_social`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `red_social`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `red_social`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenido` TEXT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `publicacion_id` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentarios_publicacion1_idx` (`publicacion_id` ASC) VISIBLE,
  INDEX `fk_comentarios_perfil1_idx` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_publicacion1`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `red_social`.`publicacion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentarios_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `red_social`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `red_social`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `red_social`.`likes` ;

CREATE TABLE IF NOT EXISTS `red_social`.`likes` (
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `publicacion_id` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  INDEX `fk_likes_publicacion1_idx` (`publicacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_likes_publicacion1`
    FOREIGN KEY (`publicacion_id`)
    REFERENCES `red_social`.`publicacion` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_likes_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `red_social`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `red_social`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `red_social`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `red_social`.`solicitudes` (
  `perfil_id_emisor` INT NOT NULL,
  `perfil_amigo_id_receptor` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`perfil_id_emisor`, `perfil_amigo_id_receptor`),
  INDEX `fk_perfil_has_perfil_perfil2_idx` (`perfil_amigo_id_receptor` ASC) VISIBLE,
  INDEX `fk_perfil_has_perfil_perfil1_idx` (`perfil_id_emisor` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_has_perfil_perfil1_solicitud`
    FOREIGN KEY (`perfil_id_emisor`)
    REFERENCES `red_social`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_perfil_has_perfil_perfil2_solicitud`
    FOREIGN KEY (`perfil_amigo_id_receptor`)
    REFERENCES `red_social`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
